FROM python:3.7

WORKDIR /code



COPY ift6758/ift6758 /app/ift6758/ift6758/
COPY serving/download_model.py .
COPY serving /app/serving


COPY ift6758/requirements.txt ./requirements.txt
RUN pip install --no-cache-dir -r requirements.txt

COPY ift6758 /app/ift6758
WORKDIR /app/ift6758
RUN pip install -e .

COPY serving/ ./serving/
ENV DOCKER_ENV_VAR=${DOCKER_ENV_VAR}

EXPOSE 8080

CMD ["python", "/app/serving/app.py"]

