services:
  flask-service:
    build:
      context: ./serving
      dockerfile: C:\Users\lenovo\Downloads\docker-project-template-main\docker-project-template-main\Dockerfile.serving
    ports:
      - "5000:5000"
    environment:
      - WANDB_API_KEY="e481c7fb933f8eadaef1ff509a063405fe4dba31"
    volumes:
      - ./serving:/app

  streamlit-service:
    build:
      context: ./streamlit
      dockerfile: C:\Users\lenovo\Downloads\docker-project-template-main\docker-project-template-main\streamlit\Dockerfile.streamlit
    ports:
      - "8501:8501"
    depends_on:
      - flask-service
    volumes:
      - ./streamlit:/app
