# version: '3.8'  # It is recommended to use a newer version

services:
  serving:
    build:
      context: ./  
      dockerfile: ./Dockerfile.serving  
    image: ift6758/serving:latest  
    ports:
      - "8080:8080"  
    environment:
      DOCKER_ENV_VAR: "${LOCAL_ENV_VAR}"  
      # WANDB_API_KEY: "${WANDB_API_KEY}"  
    volumes:
      - ./ift6758:/app/ift6758  
      - ./serving:/app/serving  
    restart: unless-stopped  
    networks:
      - app-network  

  streamlit:
    build:
      context: ./  
      dockerfile: ./Dockerfile.streamlit  

    image: ift6758/streamlit:latest  
    ports:
      - "8501:8501"  
    environment:
      OTHER_DOCKER_ENV_VAR: "${OTHER_LOCAL_ENV_VAR}"  
    volumes:
      - ./streamlit_app.py:/app/streamlit_app.py  
    restart: unless-stopped  
    networks:
      - app-network 

networks:
  app-network:
    name: app-network  
    driver: bridge
